# Generated by Django 4.1 on 2022-09-02 16:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Crypto_Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(max_length=20, null=True)),
                ('avg_price', models.FloatField(null=True)),
            ],
            options={
                'verbose_name': 'Crypto Asset',
                'verbose_name_plural': 'Crypto Assets',
            },
        ),
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model', models.CharField(max_length=200)),
                ('price', models.IntegerField()),
                ('amount', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Preset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('coords', models.FloatField()),
                ('text_color', models.CharField(max_length=200)),
                ('message_text', models.TextField()),
                ('crypto_ass', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.crypto_asset')),
            ],
            options={
                'verbose_name': 'Preset',
                'verbose_name_plural': 'Presets',
            },
        ),
    ]
