# Generated by Django 4.0.6 on 2022-07-05 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='crypto_asset',
            name='title',
            field=models.TextField(max_length=10, verbose_name='Crypto_10'),
        ),
    ]
