# Generated by Django 4.0.6 on 2022-07-05 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_crypto_asset_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_1',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_1'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_10',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_10'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_2',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_2'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_3',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_3'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_4',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_4'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_5',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_5'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_6',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_6'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_7',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_7'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_8',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_8'),
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='crypto_value_9',
            field=models.CharField(default='BTC', max_length=10, verbose_name='Crypto_9'),
        ),
        migrations.AlterField(
            model_name='crypto_asset',
            name='title',
            field=models.CharField(max_length=500, verbose_name='Name The Asset'),
        ),
    ]
