# Generated by Django 4.0.6 on 2022-07-05 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_crypto_asset_crypto_value_1_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='crypto_asset',
            options={'verbose_name': 'Crypto Asset', 'verbose_name_plural': 'Crypto Assets'},
        ),
        migrations.AddField(
            model_name='crypto_asset',
            name='description',
            field=models.TextField(default='It is my awesom setup!', max_length=1000, verbose_name='Asset Description'),
        ),
    ]
